import os

MINT_RESOURCE_PATH = os.environ["MINT_RESOURCE_PATH"]

PINATA_API_KEY = os.environ["PINATA_API_KEY"]

PINATA_SECRET_API_KEY = os.environ["PINATA_SECRET_API_KEY"]

PINATA_JWT = os.environ["PINATA_JWT"]

MINT_RPC_URL = os.environ["MINT_RPC_URL"]

MINT_CONTRACT_ADDRESS = os.environ["MINT_CONTRACT_ADDRESS"]

MINT_SIGNER_PRIVATE_KEY = os.environ["MINT_SIGNER_PRIVATE_KEY"]
